// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_WEB'),
    appId: '1:542549978836:web:045decded3e0ce02571541',
    messagingSenderId: '542549978836',
    projectId: 'roadrobos-prod',
    authDomain: 'roadrobos-prod.firebaseapp.com',
    databaseURL: 'https://roadrobos-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'roadrobos-prod.firebasestorage.app',
    measurementId: 'G-6PTKD5RFMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_ANDROID'),
    appId: '1:542549978836:android:01511e6fb66b5612571541',
    messagingSenderId: '542549978836',
    projectId: 'roadrobos-prod',
    databaseURL: 'https://roadrobos-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'roadrobos-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_IOS'),
    appId: '1:542549978836:ios:ef1b27c690f4f5ca571541',
    messagingSenderId: '542549978836',
    projectId: 'roadrobos-prod',
    databaseURL: 'https://roadrobos-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'roadrobos-prod.firebasestorage.app',
    iosClientId: '542549978836-4hemooorhcc62v77kgqaltivaagr1iih.apps.googleusercontent.com',
    iosBundleId: 'com.roadrobos.roadrobos',
  );
}
